In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import ElasticNetCV
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error,mean_squared_error
pd.set_option('display.max_rows', None)
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import confusion_matrix,classification_report

In [2]:
df = pd.read_csv(r"C:\Users\cwech\Documents\March_Madness_Train_Model.csv")

In [3]:
df.head()

,year,team,year_team,seed,Finish,First_Rd,Second_Rd,Sweet_Sixteen,Elite_Eight,Final_Four,...,Seas_Turnovers,Seas_Fouls,Seas_Opp_PPG,Seas_Opp_3PT_Succ,Seas_Opp_3PT_Rate,Seas_Opp_Off_Rebound,Seas_Opp_Def_Rebound,Seas_Opp_Turnover,Seas_Opp_Fouls,Seas_Poss
0,2012,Kentucky,2012Kentucky,1,7,1,1,1,1,1,...,11.3,14.5,59.0,0.321,0.300,0.281,0.624,11.7,18.3,67.6
1,2012,Duke,2012Duke,2,1,0,0,0,0,0,...,12.1,18.2,68.5,0.317,0.239,0.314,0.665,12.8,20.8,69.9
2,2012,Baylor,2012Baylor,3,4,1,1,1,0,0,...,13.8,17.6,65.3,0.339,0.330,0.307,0.630,14.4,18.8,68.8
3,2012,Indiana,2012Indiana,4,3,1,1,0,0,0,...,12.6,17.6,65.5,0.349,0.317,0.287,0.665,13.2,20.7,68.3
4,2012,Wichita St,2012Wichita St,5,1,0,0,0,0,0,...,11.8,17.0,62.7,0.314,0.324,0.233,0.675,12.5,18.1,69.2

In [4]:
X = df.drop(['Finish','year','team','year_team','First_Rd','Second_Rd','Sweet_Sixteen','Elite_Eight',
             'Final_Four','Championship','Pts','seed'],axis=1)
y_finish = df['Finish']
y_pts = df['Pts']

In [5]:
MM_finish_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],n_alphas=1000,eps=0.001,max_iter=100000)
MM_pts_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],n_alphas=1000,eps=0.001,max_iter=100000)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y_finish, test_size=0.25, random_state=101)

In [7]:
scaler = StandardScaler()

In [8]:
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [9]:
MM_finish_model.fit(scaled_X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000,
             n_alphas=1000)

In [10]:
y_pred_finish = MM_finish_model.predict(scaled_X_test)

In [11]:
mean_absolute_error(y_test,y_pred_finish)

1.418853173001207

In [12]:
np.sqrt(mean_squared_error(y_test,y_pred_finish))

2.225481386931159

In [13]:
MM_finish_model.get_params()

{'alphas': None,
 'copy_X': True,
 'cv': None,
 'eps': 0.001,
 'fit_intercept': True,
 'l1_ratio': [0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1],
 'max_iter': 100000,
 'n_alphas': 1000,
 'n_jobs': None,
 'positive': False,
 'precompute': 'auto',
 'random_state': None,
 'selection': 'cyclic',
 'tol': 0.0001,
 'verbose': 0}

In [14]:
coefs = pd.Series(index=X.columns,data=MM_finish_model.coef_)

In [15]:
coefs.sort_values()

Seas_3PT_Per           -1.076282
Seas_3PT_Rate          -0.961304
Seas_Opp_3PT_Succ      -0.187953
Seas_Fouls             -0.176782
Seas_Poss              -0.171985
AdjEM                  -0.163807
Seas_Opp_Fouls         -0.086614
Seas_Opp_Turnover      -0.021101
Seas_FT_Succ            0.000000
AdjT                   -0.000000
Seas_Def_Rebound_Per   -0.000000
Seas_Turnovers         -0.000000
AdjD                    0.000000
Seas_Opp_PPG           -0.000000
Seas_Opp_3PT_Rate      -0.000000
Seas_Opp_Off_Rebound    0.000000
Seas_Opp_Def_Rebound   -0.000000
Seas_Off_Rebound_Per    0.014607
Luck                    0.191620
Seas_PPG                0.407563
AdjO                    0.520768
Seas_Succ_3PT           1.330681
dtype: float64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y_pts, test_size=0.25, random_state=101)
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)
MM_pts_model.fit(scaled_X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000,
             n_alphas=1000)

In [17]:
y_pred_pts = MM_pts_model.predict(scaled_X_test)

In [18]:
mean_absolute_error(y_test,y_pred_pts)

3.781082503842129

In [19]:
np.sqrt(mean_squared_error(y_test,y_pred_pts))

6.3222889471798585

In [20]:
coefs = pd.Series(index=X.columns,data=MM_pts_model.coef_)
coefs.sort_values()

AdjD                   -0.682975
Seas_Fouls             -0.574944
Seas_Opp_Fouls         -0.438241
Seas_Opp_Def_Rebound   -0.435207
Seas_Opp_PPG           -0.153540
Seas_Def_Rebound_Per   -0.126588
Seas_Opp_3PT_Rate      -0.056094
Seas_Opp_3PT_Succ      -0.046414
Seas_Turnovers          0.000000
Seas_Poss               0.000000
Seas_Succ_3PT           0.000000
AdjT                    0.000000
Seas_3PT_Rate          -0.000000
Seas_Opp_Off_Rebound    0.098808
Seas_3PT_Per            0.108615
Seas_Opp_Turnover       0.289591
Seas_FT_Succ            0.394410
Seas_Off_Rebound_Per    0.449120
Seas_PPG                0.567856
AdjO                    0.790715
Luck                    1.166199
AdjEM                   1.974731
dtype: float64

In [21]:
pred_data = pd.read_csv(r"C:\Users\cwech\Downloads\March_Madness_2025_data.csv")

In [22]:
#pred_data = pred_data.set_index('team')
stats = pred_data.drop(['Finish','year','year_team','team','First_Rd','Second_Rd','Sweet_Sixteen','Elite_Eight',
             'Final_Four','Championship','Pts','seed'],axis=1)

In [23]:
stats_scaled = scaler.transform(stats)

In [24]:
pred_finish = MM_finish_model.predict(stats_scaled)
pred_pts = MM_pts_model.predict(stats_scaled)
pred_finish = pd.Series(index=pred_data['team'],data=pred_finish)
pred_pts = pd.Series(index=pred_data['team'],data=pred_pts)

In [25]:
q = pd.concat([pred_finish,pred_pts],axis=1)

In [26]:
q = q.reset_index()
q = q.rename(columns={1: "pts_model",0: "finish_model"})

In [27]:
q = pred_data.merge(q, how='left', on=['team'])
q = q[['team','seed','finish_model','pts_model']]

In [28]:
#q.sort_values(by='finish_model',ascending=False)

In [36]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=2, shuffle=True, random_state=42)
log_model_First_Rd = LogisticRegressionCV(cv=kf, max_iter=5000, Cs=125, penalty='l2', solver='lbfgs')
log_model_Second_Rd = LogisticRegressionCV(max_iter=5000,Cs=128, penalty='l2', solver='liblinear')
log_model_SW16 = LogisticRegressionCV(max_iter=5000,Cs=125, penalty='l2', solver='lbfgs')
log_model_E8 = LogisticRegressionCV(max_iter=5000,Cs=135, penalty='l2', solver='lbfgs')
log_model_F4 = LogisticRegressionCV(max_iter=5000,Cs=135, penalty='l2', solver='lbfgs')
log_model_Champ = LogisticRegressionCV(max_iter=5000,Cs=135, penalty='l2', solver='lbfgs')

In [37]:
X = df.drop(['Finish','year','team','year_team','First_Rd','Second_Rd','Sweet_Sixteen','Elite_Eight',
             'Final_Four','Championship','Pts','seed'],axis=1)
y_first_rd = df['First_Rd']
y_second_rd = df['Second_Rd']
y_sw16 = df['Sweet_Sixteen']
y_e8 = df['Elite_Eight']
y_f4 = df['Final_Four']
y_champ = df['Championship']

In [41]:
X.head()

550    0
598    1
2      1
287    1
653    1
780    3
713    0
560    1
640    1
256    0
764    1
109    0
433    0
234    1
135    0
106    0
687    0
225    1
719    1
683    0
339    0
763    1
667    1
754    1
237    1
64     1
706    0
698    0
434    0
389    0
188    0
29     0
39     1
6      0
501    1
531    1
738    1
672    0
492    1
23     1
651    1
481    0
18     1
148    0
290    0
4      0
533    1
34     1
454    0
584    1
60     1
747    0
353    1
130    1
48     1
407    1
146    1
445    1
525    0
782    3
573    0
804    1
326    1
72     1
562    0
58     0
544    1
306    1
80     1
391    1
248    1
233    0
62     1
213    0
111    0
314    1
663    1
805    1
693    0
820    1
216    1
811    1
697    0
429    0
86     1
198    1
611    0
212    1
807    2
176    0
53     0
117    1
206    0
124    1
725    0
272    1
458    0
520    1
363    0
495    1
459    0
587    1
568    1
173    1
293    1
467    0
63     0
164    0
131    1
54     0
308    1
733    1
751    0
155    1
175    0
545    0
331    1
773    0
261    1
265    1
595    1
338    0
160    1
509    0
731    0
332    1
622    0
263    1
252    1
0      1
260    1
413    0
38     0
104    1
307    1
532    1
30     0
278    1
178    0
236    1
816    1
614    0
812    1
318    1
57     0
423    0
159    1
694    0
388    0
464    0
572    1
360    1
373    0
317    0
224    1
659    1
255    0
809    2
661    1
489    0
621    0
801    2
690    0
700    0
205    1
19     1
452    1
384    1
766    0
342    1
753    1
522    1
655    1
351    0
824    1
670    1
156    1
791    3
161    1
468    0
593    1
345    1
831    2
65     1
795    1
282    1
449    0
720    1
548    0
286    1
476    0
355    0
746    1
823    2
400    1
673    0
636    0
737    0
491    0
321    1
312    1
624    0
372    0
166    1
563    1
324    1
283    0
527    1
479    0
181    1
142    1
78     0
660    1
382    0
707    1
448    0
472    0
482    0
325    1
427    1
95     0
28     0
349    1
822    1
121    0
616    0
555    0
367    0
652    1
543    0
392    0
189    1
834    1
170    0
15     0
701    0
796    1
684    0
301    0
758    1
179    0
91     1
567    0
729    1
836    1
313    0
399    0
361    0
769    0
756    1
69     1
627    0
195    1
536    1
200    1
730    1
41     0
70     1
439    0
259    1
631    0
66     1
547    0
43     0
292    0
500    0
688    0
199    1
551    1
37     0
790    4
426    0
296    1
143    1
630    0
798    4
832    1
165    0
133    0
794    1
605    1
691    0
421    1
466    0
583    1
710    1
51     0
132    0
44     0
645    1
814    1
120    0
315    1
783    3
748    1
613    0
243    1
702    0
695    0
154    0
411    0
524    1
728    0
504    0
193    1
222    1
597    1
220    1
271    1
13     1
431    0
842    1
722    0
211    1
17     1
153    1
14     1
73     1
800    2
671    0
443    1
586    1
538    1
93     1
778    3
344    0
666    1
786    2
775    3
215    1
521    1
396    0
387    0
480    0
150    1
810    1
511    0
297    0
152    1
662    1
302    1
602    1
494    1
646    1
169    0
415    1
745    0
45     0
409    0
618    0
112    1
398    1
277    1
496    0
380    0
437    0
829    1
569    0
765    0
310    1
390    0
541    1
405    1
102    0
238    0
25     1
712    0
559    0
430    0
158    1
20     1
289    1
330    1
629    0
376    0
590    1
502    1
617    0
819    5
453    0
119    0
588    1
251    0
579    1
594    1
444    0
759    0
401    0
679    0
245    1
145    1
350    1
689    0
752    0
221    0
311    1
515    0
85     0
680    0
177    0
108    0
242    1
115    0
35     1
441    0
549    1
546    1
1      0
490    0
705    0
571    1
101    0
369    0
830    1
11     1
456    0
837    1
223    1
537    0
163    0
770    0
635    0
422    0
639    1
359    1
488    0
833    1
192    1
208    1
755    0
736    1
828    1
97     1
734    0
377    0
22     1
554    0
348    1
518    1
743    0
591    1
88     1
50     0
592    1
566    0
232    1
578    1
813    2
26     1
469    0
724    0
487    1
718    1
122    0
96     1
190    0
772    1
596    1
455    0
144    1
699    0
726    1
87     1
412    0
270    1
658    1
61     1
484    1
580    1
79     0
129    1
67     1
564    0
125    0
649    1
678    0
609    0
219    1
825    1
395    0
309    0
285    0
370    0
692    0
404    0
280    1
397    0
253    1
52     0
561    0
716    0
654    1
696    0
727    0
358    1
589    1
82     1
777    6
217    1
305    1
827    1
539    0
711    1
356    1
94     1
383    0
254    0
235    1
535    0
465    0
21     1
768    0
149    1
470    1
508    1
558    1
643    1
46     0
461    0
451    0
226    1
207    1
675    0
244    0
357    1
71     1
366    0
229    0
103    0
262    1
632    0
197    1
505    0
709    0
250    1
526    0
303    1
340    1
3      1
540    0
774    1
478    0
625    0
394    0
507    0
92     0
806    2
570    1
792    3
386    0
685    0
137    1
214    1
741    1
47     0
686    0
771    0
378    1
276    1
789    5
499    1
10     1
542    1
419    1
498    0
815    1
703    0
803    1
664    1
463    0
203    1
760    0
273    1
140    0
362    1
628    0
512    1
300    1
797    1
327    1
808    2
402    0
799    2
329    1
750    1
294    0
615    0
440    0
436    0
519    0
284    1
99     1
676    0
574    0
264    1
239    0
457    0
503    0
105    0
343    1
619    0
735    1
76     0
638    0
275    0
249    0
556    0
418    0
59     0
371    0
136    1
506    0
623    0
49     0
40     1
477    1
5      0
110    1
704    0
732    0
316    0
757    1
839    1
644    1
552    1
393    0
75     0
599    1
575    1
838    1
337    1
523    1
Name: First_Rd, dtype: int64

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y_first_rd, test_size=0.25, random_state=101)
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)
log_model_First_Rd.fit(scaled_X_train,y_train)

ValueError: cannot reshape array of size 34500 into shape (2,125,7,newaxis)

In [ ]:
# Set up parameter grid
#param_grid = {
#    'Cs': [135,145,140],
#    'solver': ['lbfgs']
#}

# Create grid search object
#grid_search = GridSearchCV(log_model_E8, param_grid, cv=5)

# Fit the grid search object to the data
#grid_search.fit(scaled_X_train, y_train)

# Print the best parameters
#print(grid_search.best_params_)

In [ ]:
coefs = pd.Series(index=X.columns,data=log_model_First_Rd.coef_[0])
coefs.sort_values()

In [ ]:
y_pred_frd = log_model_First_Rd.predict(scaled_X_test)

In [ ]:
print(classification_report(y_test,y_pred_frd))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_second_rd, test_size=0.25, random_state=101)
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)
log_model_Second_Rd.fit(scaled_X_train,y_train)
y_pred_srd = log_model_Second_Rd.predict(scaled_X_test)
print(classification_report(y_test,y_pred_srd))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_sw16, test_size=0.25, random_state=101)
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)
log_model_SW16.fit(scaled_X_train,y_train)
y_pred_sw16 = log_model_SW16.predict(scaled_X_test)
print(classification_report(y_test,y_pred_sw16))

In [ ]:
coefs = pd.Series(index=X.columns,data=log_model_SW16.coef_[0])
coefs.sort_values()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_e8, test_size=0.25, random_state=101)
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)
log_model_E8.fit(scaled_X_train,y_train)
y_pred_e8 = log_model_E8.predict(scaled_X_test)
print(classification_report(y_test,y_pred_e8))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_f4, test_size=0.25, random_state=101)
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)
log_model_F4.fit(scaled_X_train,y_train)
y_pred_f4 = log_model_F4.predict(scaled_X_test)
print(classification_report(y_test,y_pred_f4))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y_champ, test_size=0.25, random_state=101)
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)
log_model_Champ.fit(scaled_X_train,y_train)
y_pred_champ = log_model_Champ.predict(scaled_X_test)
print(classification_report(y_test,y_pred_champ))

In [ ]:
pred_frd = log_model_First_Rd.predict_proba(stats_scaled)
pred_srd = log_model_Second_Rd.predict_proba(stats_scaled)
pred_sw16 = log_model_SW16.predict_proba(stats_scaled)
pred_e8 = log_model_E8.predict_proba(stats_scaled)
pred_f4 = log_model_F4.predict_proba(stats_scaled)
pred_champ = log_model_Champ.predict_proba(stats_scaled)
pred_frd = pd.DataFrame(index=pred_data['team'],data=pred_frd)
pred_srd = pd.DataFrame(index=pred_data['team'],data=pred_srd)
pred_sw16 = pd.DataFrame(index=pred_data['team'],data=pred_sw16)
pred_e8 = pd.DataFrame(index=pred_data['team'],data=pred_e8)
pred_f4 = pd.DataFrame(index=pred_data['team'],data=pred_f4)
pred_champ = pd.DataFrame(index=pred_data['team'],data=pred_champ)

In [ ]:
pred_frd = pred_frd.reset_index()
pred_frd = pred_frd.drop(0,axis=1)
pred_frd = pred_frd.rename(columns={1: "First_Round"})
pred_srd = pred_srd.reset_index()
pred_srd = pred_srd.drop(0,axis=1)
pred_srd = pred_srd.rename(columns={1: "Second_Round"})
pred_sw16 = pred_sw16.reset_index()
pred_sw16 = pred_sw16.drop(0,axis=1)
pred_sw16 = pred_sw16.rename(columns={1: "Sweet_Sixteen"})
pred_e8 = pred_e8.reset_index()
pred_e8 = pred_e8.drop(0,axis=1)
pred_e8 = pred_e8.rename(columns={1: "Elite_Eight"})
pred_f4 = pred_f4.reset_index()
pred_f4 = pred_f4.drop(0,axis=1)
pred_f4 = pred_f4.rename(columns={1: "Final_Four"})
pred_champ = pred_champ.reset_index()
pred_champ = pred_champ.drop(0,axis=1)
pred_champ = pred_champ.rename(columns={1: "Champ"})

In [ ]:
q = pred_frd.merge(q, how='left', on=['team'])

In [ ]:
q = pred_srd.merge(q, how='left', on=['team'])
q = pred_sw16.merge(q, how='left', on=['team'])
q = pred_e8.merge(q, how='left', on=['team'])
q = pred_f4.merge(q, how='left', on=['team'])
q = pred_champ.merge(q, how='left', on=['team'])

In [28]:
X = df.drop(['Finish','year','team','year_team','First_Rd','Second_Rd','Sweet_Sixteen','Elite_Eight',
             'Final_Four','Championship','Pts','seed'],axis=1)
y_finish = df['Finish']
X_train, X_test, y_train, y_test = train_test_split(X, y_finish, test_size=0.25, random_state=101)
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)
model = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=500, learning_rate=0.01, max_depth=3,colsample_bytree=0.7,reg_alpha=1,reg_lambda=0,subsample=0.5)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE: %f" % (rmse))
pred_xgb = model.predict(stats_scaled)
pred_xgb = pd.DataFrame(index=pred_data['team'],data=pred_xgb)
pred_xgb = pred_xgb.reset_index()
pred_xgb = pred_xgb.rename(columns={0: "XGB"})
q = pred_xgb.merge(q, how='left', on=['team'])

RMSE: 1.671824

In [29]:
#params = {'objective': ['reg:squarederror', 'reg:linear', 'reg:gamma','reg:tweedie','binary:logistic','multi:softmax','multi:softprob']}
#grid_search = GridSearchCV(estimator=model, param_grid=params, cv=5, n_jobs=-1)
#grid_search.fit(X_train, y_train)
# Print the best hyperparameters and the corresponding score
#print("Best parameters: ", grid_search.best_params_)
#print("Best score: ", grid_search.best_score_)

In [30]:
#q = q[['team', 'seed','XGB','finish_model', 'pts_model', 'First_Round','Second_Round','Sweet_Sixteen','Elite_Eight','Final_Four','Champ']]
q = q[['team', 'seed','XGB','finish_model', 'pts_model']]
q = q.sort_values(by='finish_model',ascending=False)

In [31]:
q

              team  seed        XGB  finish_model  pts_model
67      Norfolk St    16   7.776198      9.688415  -2.133470
30         Gonzaga     8   7.713055      9.039296   7.056222
50            Yale    13   8.301223      8.795537   0.854977
4      Michigan St     2   7.111074      8.385477   7.521629
19         Memphis     5   9.617240      8.286413   5.643379
7        St John's     2   8.575105      7.921970   7.720233
25    Saint Mary's     7   9.205199      7.755526   7.229794
13         Arizona     4  10.004875      7.694732   7.164171
2          Houston     1   7.328524      7.338193  12.519576
36      New Mexico    10   9.758140      7.315460   2.506829
55         Montana    14   8.244427      7.282778   0.098698
14          Purdue     4   9.973069      7.218339   6.049129
27          Kansas     7   9.912879      7.120396   5.830530
15        Maryland     4  10.128001      7.083960   7.363876
53    Grand Canyon    13   8.250933      6.996840   0.239497
52      High Point    13   8.237369      6.843632   1.788018
57   NC Wilmington    14   7.993165      6.720591   1.322823
8          Iowa St     3  10.266789      6.698596   7.274467
43           Texas    11  10.130678      6.588390   1.338861
41  North Carolina    10  10.084693      6.561033   3.345016
0           Auburn     1   7.105665      6.408888  11.890078
45           Drake    11   8.379366      6.358469   3.133998
48         McNeese    12   8.751522      6.269436   3.326629
34         Georgia     9   9.636190      6.250231   4.510044
44          Xavier    11  10.047865      6.229141   2.497220
58          Bryant    15   7.608468      6.085263  -1.313261
23        Missouri     6   9.510165      6.033567   5.870036
26            UCLA     7   9.576782      5.979884   5.257675
39        Arkansas    10  10.034019      5.814365   2.821098
17          Oregon     5  10.137378      5.703353   6.821799
18         Clemson     5   9.824384      5.682163   7.459778
59   Robert Morris    15   7.501259      5.564680   1.008785
10        Kentucky     3   9.754529      5.434640   5.961283
61           Omaha    15   7.361233      5.275231  -2.422285
38         Utah St    10   9.199052      5.130371   5.007801
3          Florida     1   7.100674      4.963942  12.994675
12       Texas A&M     4   8.959189      4.947844   6.562756
35        Oklahoma     9  10.185950      4.895955   3.672184
1             Duke     1   6.304642      4.508874  13.440399
37      Vanderbilt    10  10.101858      4.490999   4.241397
33          Baylor     9   9.811916      4.467465   5.095573
66      SIU Edward    16   8.003454      4.409629  -4.086166
20     Mississippi     6   9.940814      4.381585   4.450093
5          Alabama     2   7.092377      4.362811   9.016893
6        Tennessee     2   7.207463      4.352886  10.222514
31           UConn     8   9.375996      3.987452   5.321219
16        Michigan     5   9.629286      3.960081   7.175010
11      Texas Tech     3   5.845830      3.765831   8.727739
49     Colorado St    12  10.039175      3.738875   3.450997
40    San Diego St    10   9.869110      3.463057   1.266687
29  Mississippi St     8   8.784701      3.408278   5.251306
64    Mt St Mary's    16   7.720216      3.243478  -1.637085
51           Akron    13   7.339988      2.943880   2.895007
54        Lipscomb    14   7.125342      2.507043   1.359464
22        Illinois     6   8.994144      2.496645   6.986367
21             BYU     6   7.965455      2.085700   7.515100
47         Liberty    12   7.325153      2.075888   1.030078
9        Wisconsin     3   8.729473      2.061487   5.994872
62   St Francis PA    16   8.032392      1.886515  -6.140300
28      Louisville     8   9.649102      1.856109   7.843944
24       Marquette     7   8.638813      1.742221   6.180625
32       Creighton     9   8.014033      1.706670   6.160422
56            Troy    14   7.755615      1.691912   1.475923
42             VCU    11   8.040235      1.446730   5.550550
65        American    16   6.231924      1.247326  -3.174574
46            UCSD    12   8.651527      0.871053   4.711788
63      Alabama St    16   7.327395      0.811700  -5.847780
60         Wofford    15   6.576761      0.620368  -2.310128

In [32]:
q.to_excel(r"C:\Users\cwech\Documents\Big_Dance_Results_no_seed.xlsx",
             sheet_name='Results',index=False)